### ISSUE TITLE
Gpio::new() PermissionDenied

### ISSUE THREAD

**Issue by NealEhardt** [golemparts/rppal#15] opened 2018-12-20 04:26 UTC
Consider the following program:

    extern crate rppal;
    
    fn main() {
        rppal::gpio::Gpio::new().unwrap();
    }

Using rppal 0.8.0 or higher on Raspberry Pi, I get a Permission error:

>thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })', libcore/result.rs:1009:5

But it runs fine on rppal 0.7.1. And with a longer program, I'm able to read and write to GPIO.

So it looks like this is a regression introduced between 0.7.1 and 0.8.0.

Raspberry Pi 3 Model B Rev 1.2
OS: Raspbian GNU/Linux 8 (jessie)
rustc: 1.31.0

**Comment by golemparts** [comment] 2018-12-20 08:02
Thanks for reporting this issue. As far as I can tell, there aren't any changes going from 0.7.1 to 0.8.0 that change the way the GPIO peripheral is accessed, but perhaps I missed something.

Can you post the output of `ls -l /dev/*mem && groups && uname -a` to make sure it's not caused by an actual permissions issue?

**Comment by NealEhardt** [comment] 2018-12-20 23:51
Sure, here you go:

    pi@glados:~ $ ls -l /dev/*mem && groups && uname -a
    crw-rw---- 1 root gpio 243, 0 Dec 16 16:17 /dev/gpiomem
    crw-r----- 1 root kmem   1, 1 Dec 16 16:17 /dev/mem
    crw------- 1 root root 249, 0 Dec 16 16:17 /dev/vc-mem
    pi adm dialout cdrom sudo audio video plugdev games users input netdev gpio i2c spi
    Linux glados 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux

I see that 0.8.0 is failing on [open /dev/gpiochip here](https://github.com/golemparts/rppal/blob/0.8.0/src/gpio/ioctl.rs#L318). If I change the `?` to `.unwrap()`, I get the PermissionDenied there.

A text search of rppal 0.7.1 shows no result for "gpiochip".

    pi@glados:~ $ ls -l /dev/gpiochip*
    crw------- 1 root root 254, 0 Dec 16 16:17 /dev/gpiochip0
    crw------- 1 root root 254, 1 Dec 16 16:17 /dev/gpiochip1
    crw------- 1 root root 254, 2 Dec 16 16:17 /dev/gpiochip2

After I run `sudo chown root.gpio /dev/gpiochip* && sudo chmod g+rw /dev/gpiochip*` then rppal 0.8.0 and 0.10.0 start working. After I reboot, the settings revert and the latest rppal versions are broken.

**Comment by golemparts** [comment] 2018-12-21 00:52
For reference, this is what the GPIO-related parts of my `/etc/udev/rules.d/99-com.rules` look like, although I'm not sure if these are also triggered when the /dev/gpiochipN files are created, and if it would work on your older kernel. It would be safest to just update everything to the latest release.

```
SUBSYSTEM=="bcm2835-gpiomem", GROUP="gpio", MODE="0660"

SUBSYSTEM=="gpio", GROUP="gpio", MODE="0660"
SUBSYSTEM=="gpio*", PROGRAM="/bin/sh -c '\
	chown -R root:gpio /sys/class/gpio && chmod -R 770 /sys/class/gpio;\
	chown -R root:gpio /sys/devices/virtual/gpio && chmod -R 770 /sys/devices/virtual/gpio;\
	chown -R root:gpio /sys$devpath && chmod -R 770 /sys$devpath\
'"
```

**Comment by golemparts** [comment] 2018-12-21 01:13
I found the related issue https://github.com/raspberrypi/linux/issues/2289

Looks like this was fixed in a Raspbian release after November 2017.

**Comment by NealEhardt** [comment] 2018-12-21 17:05
I was actually running kernel 4.14.89 for those last tests. Seems like you only get the permissions with a clean Raspbian install.

I had to edit `/etc/udev/rules.d/99-com.rules` manually to insert the rule, [just like this commit](https://github.com/RPi-Distro/raspberrypi-sys-mods/commit/bd5a201475b14c7f00add8d8e5f5cd018ad15d8b#diff-2678c183f503319c8d8c09c818af789aR6). Then `sudo reboot` and everything works.

In the docs, you might just link to this issue. Thanks for your patience in helping me to resolve this.

**Comment by golemparts** [comment] 2018-12-21 17:07
No problem! I'm glad you can now move on to rppal v0.10. 😄

**Closed by golemparts** 2018-12-21 17:07 UTC
